version: "3.8"

services:
  backend:
    image: whitesnek/sd_009_backend:latest
    container_name: backend
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    image: whitesnek/sd_009:latest
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
